[2024-04-04T01:07:04.676-0500] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: SlowChangingDimension_1.queryPostgresSaveFile scheduled__2024-04-03T00:00:00+00:00 [queued]>
[2024-04-04T01:07:04.679-0500] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: SlowChangingDimension_1.queryPostgresSaveFile scheduled__2024-04-03T00:00:00+00:00 [queued]>
[2024-04-04T01:07:04.679-0500] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-04-04T01:07:04.683-0500] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): queryPostgresSaveFile> on 2024-04-03 00:00:00+00:00
[2024-04-04T01:07:04.687-0500] {standard_task_runner.py:60} INFO - Started process 32577 to run task
[2024-04-04T01:07:04.692-0500] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'SlowChangingDimension_1', 'queryPostgresSaveFile', 'scheduled__2024-04-03T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/scd_0.py', '--cfg-path', '/var/folders/vv/q_fdzqpd787cn9t82l571nsw0000gn/T/tmppojwpljy']
[2024-04-04T01:07:04.693-0500] {standard_task_runner.py:88} INFO - Job 4: Subtask queryPostgresSaveFile
[2024-04-04T01:07:04.712-0500] {task_command.py:423} INFO - Running <TaskInstance: SlowChangingDimension_1.queryPostgresSaveFile scheduled__2024-04-03T00:00:00+00:00 [running]> on host laxminayanasair.lan
[2024-04-04T01:07:04.728-0500] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='laxminarayana.vadnala@slu.edu' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='SlowChangingDimension_1' AIRFLOW_CTX_TASK_ID='queryPostgresSaveFile' AIRFLOW_CTX_EXECUTION_DATE='2024-04-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-03T00:00:00+00:00'
[2024-04-04T01:07:04.729-0500] {sql.py:276} INFO - Executing: SELECT * FROM test
[2024-04-04T01:07:04.732-0500] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Volumes/SLU_CS/big_data_scd_all_types_project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/SLU_CS/big_data_scd_all_types_project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/SLU_CS/big_data_scd_all_types_project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/SLU_CS/big_data_scd_all_types_project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/SLU_CS/big_data_scd_all_types_project/airflow/dags/scd_0.py", line 33, in save_file
    pg_result = step_1.execute(context={})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/SLU_CS/big_data_scd_all_types_project/.venv/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/Volumes/SLU_CS/big_data_scd_all_types_project/.venv/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/Users/laxminarayanavadnala/anaconda3/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/Volumes/SLU_CS/big_data_scd_all_types_project/.venv/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/SLU_CS/big_data_scd_all_types_project/.venv/lib/python3.11/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/SLU_CS/big_data_scd_all_types_project/.venv/lib/python3.11/site-packages/airflow/models/connection.py", line 514, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `transactional_db_uri` isn't defined
[2024-04-04T01:07:04.735-0500] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=SlowChangingDimension_1, task_id=queryPostgresSaveFile, execution_date=20240403T000000, start_date=20240404T060704, end_date=20240404T060704
[2024-04-04T01:07:04.739-0500] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task queryPostgresSaveFile (The conn_id `transactional_db_uri` isn't defined; 32577)
[2024-04-04T01:07:04.752-0500] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-04T01:07:04.759-0500] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
